development: &default
  adapter: postgresql
  database: ads_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000
  username: postadmin  
  password: hello
development:
  <<: *default
  adapter:  postgresql
  database: ads_development

production:
  <<: *default
  database: ads_production

